### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by takedowndmca** [luisgbr1el/kelle-telegram#4]
there has been an error on line 48, please help

`(node:9208) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (C:\negets\m3u8\sesibot\node_modules\@phaticusthiccy\open-apis\node_modules\axios\lib\core\createError.js:16:15)        
    at settle (C:\negets\m3u8\sesibot\node_modules\@phaticusthiccy\open-apis\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\negets\m3u8\sesibot\node_modules\@phaticusthiccy\open-apis\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by takedowndmca** [comment]
Turns out the tiktok video link has been removed...
_https://www.tiktok.com/@storyanakkuburan_/video/7091292328870022427_
![image](https://user-images.githubusercontent.com/81884848/165915442-1d2b9165-ed90-4a13-bbc1-5a70d529fb8e.png)
Sorry I didn't check the link carefully, thanks.
